// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DatabaseContext;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Models.CountSheet", b =>
                {
                    b.Property<string>("CountCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cnt_code");

                    b.Property<DateTime>("CountDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cnt_date");

                    b.Property<string>("CountDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("cnt_desc");

                    b.Property<string>("CountSheetEmployee")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cnt_emp");

                    b.Property<int>("CountStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("cnt_status");

                    b.HasKey("CountCode");

                    b.ToTable("count_sheet", (string)null);
                });

            modelBuilder.Entity("WebApplication2.Models.ItemCount", b =>
                {
                    b.Property<int>("ItemCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("itm_ctr");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemCounter"));

                    b.Property<string>("ItemBatchLotNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("itm_batchlot");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("itm_code");

                    b.Property<string>("ItemCountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("itm_cntcode");

                    b.Property<DateTime>("ItemDateLog")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("itm_date_log");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("itm_description");

                    b.Property<string>("ItemExpiry")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("itm_expiry");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("itm_key");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int")
                        .HasColumnName("itm_quantity");

                    b.Property<string>("ItemUom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("itm_uom");

                    b.HasKey("ItemCounter");

                    b.ToTable("item_count", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
